//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace Transfer8Pro.WebApp.OBWebService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiceSoap", Namespace="http://www.openbook.com.cn/")]
    public partial class Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private OBSoapHeader oBSoapHeaderValueField;
        
        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSerialNoOperationCompleted;
        
        private System.Threading.SendOrPostCallback TryLoginOperationCompleted;
        
        private System.Threading.SendOrPostCallback ChangePwdOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllEmpInfoForPageForOBFACEOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllDeptInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetEmpDetailedInfoByUserIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUserInfoByDeptIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetEmpInfoForPageByParentIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllEmpInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllUserBySysIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateUserStateBySysIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetGroupListByDeptIDOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service() {
            this.Url = global::Transfer8Pro.WebApp.Properties.Settings.Default.Transfer8Pro_WebApp_OBWebService_Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public OBSoapHeader OBSoapHeaderValue {
            get {
                return this.oBSoapHeaderValueField;
            }
            set {
                this.oBSoapHeaderValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;
        
        /// <remarks/>
        public event GetSerialNoCompletedEventHandler GetSerialNoCompleted;
        
        /// <remarks/>
        public event TryLoginCompletedEventHandler TryLoginCompleted;
        
        /// <remarks/>
        public event ChangePwdCompletedEventHandler ChangePwdCompleted;
        
        /// <remarks/>
        public event GetAllEmpInfoForPageForOBFACECompletedEventHandler GetAllEmpInfoForPageForOBFACECompleted;
        
        /// <remarks/>
        public event GetAllDeptInfoCompletedEventHandler GetAllDeptInfoCompleted;
        
        /// <remarks/>
        public event GetEmpDetailedInfoByUserIDCompletedEventHandler GetEmpDetailedInfoByUserIDCompleted;
        
        /// <remarks/>
        public event GetUserInfoByDeptIDCompletedEventHandler GetUserInfoByDeptIDCompleted;
        
        /// <remarks/>
        public event GetEmpInfoForPageByParentIDCompletedEventHandler GetEmpInfoForPageByParentIDCompleted;
        
        /// <remarks/>
        public event GetAllEmpInfoCompletedEventHandler GetAllEmpInfoCompleted;
        
        /// <remarks/>
        public event GetAllUserBySysIDCompletedEventHandler GetAllUserBySysIDCompleted;
        
        /// <remarks/>
        public event UpdateUserStateBySysIDCompletedEventHandler UpdateUserStateBySysIDCompleted;
        
        /// <remarks/>
        public event GetGroupListByDeptIDCompletedEventHandler GetGroupListByDeptIDCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("OBSoapHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.openbook.com.cn/HelloWorld", RequestNamespace="http://www.openbook.com.cn/", ResponseNamespace="http://www.openbook.com.cn/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        /// <remarks/>
        public void HelloWorldAsync(object userState) {
            if ((this.HelloWorldOperationCompleted == null)) {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
        }
        
        private void OnHelloWorldOperationCompleted(object arg) {
            if ((this.HelloWorldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("OBSoapHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.openbook.com.cn/GetSerialNo", RequestNamespace="http://www.openbook.com.cn/", ResponseNamespace="http://www.openbook.com.cn/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetSerialNo(int type) {
            object[] results = this.Invoke("GetSerialNo", new object[] {
                        type});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetSerialNoAsync(int type) {
            this.GetSerialNoAsync(type, null);
        }
        
        /// <remarks/>
        public void GetSerialNoAsync(int type, object userState) {
            if ((this.GetSerialNoOperationCompleted == null)) {
                this.GetSerialNoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSerialNoOperationCompleted);
            }
            this.InvokeAsync("GetSerialNo", new object[] {
                        type}, this.GetSerialNoOperationCompleted, userState);
        }
        
        private void OnGetSerialNoOperationCompleted(object arg) {
            if ((this.GetSerialNoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSerialNoCompleted(this, new GetSerialNoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("OBSoapHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.openbook.com.cn/TryLogin", RequestNamespace="http://www.openbook.com.cn/", ResponseNamespace="http://www.openbook.com.cn/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool TryLogin(string loginname, string pwd, string sys, out string userid) {
            object[] results = this.Invoke("TryLogin", new object[] {
                        loginname,
                        pwd,
                        sys});
            userid = ((string)(results[1]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void TryLoginAsync(string loginname, string pwd, string sys) {
            this.TryLoginAsync(loginname, pwd, sys, null);
        }
        
        /// <remarks/>
        public void TryLoginAsync(string loginname, string pwd, string sys, object userState) {
            if ((this.TryLoginOperationCompleted == null)) {
                this.TryLoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTryLoginOperationCompleted);
            }
            this.InvokeAsync("TryLogin", new object[] {
                        loginname,
                        pwd,
                        sys}, this.TryLoginOperationCompleted, userState);
        }
        
        private void OnTryLoginOperationCompleted(object arg) {
            if ((this.TryLoginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TryLoginCompleted(this, new TryLoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("OBSoapHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.openbook.com.cn/ChangePwd", RequestNamespace="http://www.openbook.com.cn/", ResponseNamespace="http://www.openbook.com.cn/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int ChangePwd(string userid, string oldpass, string newpass) {
            object[] results = this.Invoke("ChangePwd", new object[] {
                        userid,
                        oldpass,
                        newpass});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void ChangePwdAsync(string userid, string oldpass, string newpass) {
            this.ChangePwdAsync(userid, oldpass, newpass, null);
        }
        
        /// <remarks/>
        public void ChangePwdAsync(string userid, string oldpass, string newpass, object userState) {
            if ((this.ChangePwdOperationCompleted == null)) {
                this.ChangePwdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnChangePwdOperationCompleted);
            }
            this.InvokeAsync("ChangePwd", new object[] {
                        userid,
                        oldpass,
                        newpass}, this.ChangePwdOperationCompleted, userState);
        }
        
        private void OnChangePwdOperationCompleted(object arg) {
            if ((this.ChangePwdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ChangePwdCompleted(this, new ChangePwdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("OBSoapHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.openbook.com.cn/GetAllEmpInfoForPageForOBFACE", RequestNamespace="http://www.openbook.com.cn/", ResponseNamespace="http://www.openbook.com.cn/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetAllEmpInfoForPageForOBFACE(string username, int deptid, int groupid, int usersex, int PageSize, int PageIndex, out int Records) {
            object[] results = this.Invoke("GetAllEmpInfoForPageForOBFACE", new object[] {
                        username,
                        deptid,
                        groupid,
                        usersex,
                        PageSize,
                        PageIndex});
            Records = ((int)(results[1]));
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetAllEmpInfoForPageForOBFACEAsync(string username, int deptid, int groupid, int usersex, int PageSize, int PageIndex) {
            this.GetAllEmpInfoForPageForOBFACEAsync(username, deptid, groupid, usersex, PageSize, PageIndex, null);
        }
        
        /// <remarks/>
        public void GetAllEmpInfoForPageForOBFACEAsync(string username, int deptid, int groupid, int usersex, int PageSize, int PageIndex, object userState) {
            if ((this.GetAllEmpInfoForPageForOBFACEOperationCompleted == null)) {
                this.GetAllEmpInfoForPageForOBFACEOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllEmpInfoForPageForOBFACEOperationCompleted);
            }
            this.InvokeAsync("GetAllEmpInfoForPageForOBFACE", new object[] {
                        username,
                        deptid,
                        groupid,
                        usersex,
                        PageSize,
                        PageIndex}, this.GetAllEmpInfoForPageForOBFACEOperationCompleted, userState);
        }
        
        private void OnGetAllEmpInfoForPageForOBFACEOperationCompleted(object arg) {
            if ((this.GetAllEmpInfoForPageForOBFACECompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllEmpInfoForPageForOBFACECompleted(this, new GetAllEmpInfoForPageForOBFACECompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("OBSoapHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.openbook.com.cn/GetAllDeptInfo", RequestNamespace="http://www.openbook.com.cn/", ResponseNamespace="http://www.openbook.com.cn/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetAllDeptInfo() {
            object[] results = this.Invoke("GetAllDeptInfo", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetAllDeptInfoAsync() {
            this.GetAllDeptInfoAsync(null);
        }
        
        /// <remarks/>
        public void GetAllDeptInfoAsync(object userState) {
            if ((this.GetAllDeptInfoOperationCompleted == null)) {
                this.GetAllDeptInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllDeptInfoOperationCompleted);
            }
            this.InvokeAsync("GetAllDeptInfo", new object[0], this.GetAllDeptInfoOperationCompleted, userState);
        }
        
        private void OnGetAllDeptInfoOperationCompleted(object arg) {
            if ((this.GetAllDeptInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllDeptInfoCompleted(this, new GetAllDeptInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("OBSoapHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.openbook.com.cn/GetEmpDetailedInfoByUserID", RequestNamespace="http://www.openbook.com.cn/", ResponseNamespace="http://www.openbook.com.cn/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetEmpDetailedInfoByUserID(string userid) {
            object[] results = this.Invoke("GetEmpDetailedInfoByUserID", new object[] {
                        userid});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetEmpDetailedInfoByUserIDAsync(string userid) {
            this.GetEmpDetailedInfoByUserIDAsync(userid, null);
        }
        
        /// <remarks/>
        public void GetEmpDetailedInfoByUserIDAsync(string userid, object userState) {
            if ((this.GetEmpDetailedInfoByUserIDOperationCompleted == null)) {
                this.GetEmpDetailedInfoByUserIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetEmpDetailedInfoByUserIDOperationCompleted);
            }
            this.InvokeAsync("GetEmpDetailedInfoByUserID", new object[] {
                        userid}, this.GetEmpDetailedInfoByUserIDOperationCompleted, userState);
        }
        
        private void OnGetEmpDetailedInfoByUserIDOperationCompleted(object arg) {
            if ((this.GetEmpDetailedInfoByUserIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetEmpDetailedInfoByUserIDCompleted(this, new GetEmpDetailedInfoByUserIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("OBSoapHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.openbook.com.cn/GetUserInfoByDeptID", RequestNamespace="http://www.openbook.com.cn/", ResponseNamespace="http://www.openbook.com.cn/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetUserInfoByDeptID(int deptid) {
            object[] results = this.Invoke("GetUserInfoByDeptID", new object[] {
                        deptid});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetUserInfoByDeptIDAsync(int deptid) {
            this.GetUserInfoByDeptIDAsync(deptid, null);
        }
        
        /// <remarks/>
        public void GetUserInfoByDeptIDAsync(int deptid, object userState) {
            if ((this.GetUserInfoByDeptIDOperationCompleted == null)) {
                this.GetUserInfoByDeptIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUserInfoByDeptIDOperationCompleted);
            }
            this.InvokeAsync("GetUserInfoByDeptID", new object[] {
                        deptid}, this.GetUserInfoByDeptIDOperationCompleted, userState);
        }
        
        private void OnGetUserInfoByDeptIDOperationCompleted(object arg) {
            if ((this.GetUserInfoByDeptIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUserInfoByDeptIDCompleted(this, new GetUserInfoByDeptIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("OBSoapHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.openbook.com.cn/GetEmpInfoForPageByParentID", RequestNamespace="http://www.openbook.com.cn/", ResponseNamespace="http://www.openbook.com.cn/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetEmpInfoForPageByParentID(string parentid, int PageSize, int PageIndex, out int Records) {
            object[] results = this.Invoke("GetEmpInfoForPageByParentID", new object[] {
                        parentid,
                        PageSize,
                        PageIndex});
            Records = ((int)(results[1]));
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetEmpInfoForPageByParentIDAsync(string parentid, int PageSize, int PageIndex) {
            this.GetEmpInfoForPageByParentIDAsync(parentid, PageSize, PageIndex, null);
        }
        
        /// <remarks/>
        public void GetEmpInfoForPageByParentIDAsync(string parentid, int PageSize, int PageIndex, object userState) {
            if ((this.GetEmpInfoForPageByParentIDOperationCompleted == null)) {
                this.GetEmpInfoForPageByParentIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetEmpInfoForPageByParentIDOperationCompleted);
            }
            this.InvokeAsync("GetEmpInfoForPageByParentID", new object[] {
                        parentid,
                        PageSize,
                        PageIndex}, this.GetEmpInfoForPageByParentIDOperationCompleted, userState);
        }
        
        private void OnGetEmpInfoForPageByParentIDOperationCompleted(object arg) {
            if ((this.GetEmpInfoForPageByParentIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetEmpInfoForPageByParentIDCompleted(this, new GetEmpInfoForPageByParentIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("OBSoapHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.openbook.com.cn/GetAllEmpInfo", RequestNamespace="http://www.openbook.com.cn/", ResponseNamespace="http://www.openbook.com.cn/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetAllEmpInfo() {
            object[] results = this.Invoke("GetAllEmpInfo", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetAllEmpInfoAsync() {
            this.GetAllEmpInfoAsync(null);
        }
        
        /// <remarks/>
        public void GetAllEmpInfoAsync(object userState) {
            if ((this.GetAllEmpInfoOperationCompleted == null)) {
                this.GetAllEmpInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllEmpInfoOperationCompleted);
            }
            this.InvokeAsync("GetAllEmpInfo", new object[0], this.GetAllEmpInfoOperationCompleted, userState);
        }
        
        private void OnGetAllEmpInfoOperationCompleted(object arg) {
            if ((this.GetAllEmpInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllEmpInfoCompleted(this, new GetAllEmpInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("OBSoapHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.openbook.com.cn/GetAllUserBySysID", RequestNamespace="http://www.openbook.com.cn/", ResponseNamespace="http://www.openbook.com.cn/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetAllUserBySysID(int sysid) {
            object[] results = this.Invoke("GetAllUserBySysID", new object[] {
                        sysid});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetAllUserBySysIDAsync(int sysid) {
            this.GetAllUserBySysIDAsync(sysid, null);
        }
        
        /// <remarks/>
        public void GetAllUserBySysIDAsync(int sysid, object userState) {
            if ((this.GetAllUserBySysIDOperationCompleted == null)) {
                this.GetAllUserBySysIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllUserBySysIDOperationCompleted);
            }
            this.InvokeAsync("GetAllUserBySysID", new object[] {
                        sysid}, this.GetAllUserBySysIDOperationCompleted, userState);
        }
        
        private void OnGetAllUserBySysIDOperationCompleted(object arg) {
            if ((this.GetAllUserBySysIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllUserBySysIDCompleted(this, new GetAllUserBySysIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("OBSoapHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.openbook.com.cn/UpdateUserStateBySysID", RequestNamespace="http://www.openbook.com.cn/", ResponseNamespace="http://www.openbook.com.cn/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool UpdateUserStateBySysID(string userid, int sysid) {
            object[] results = this.Invoke("UpdateUserStateBySysID", new object[] {
                        userid,
                        sysid});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateUserStateBySysIDAsync(string userid, int sysid) {
            this.UpdateUserStateBySysIDAsync(userid, sysid, null);
        }
        
        /// <remarks/>
        public void UpdateUserStateBySysIDAsync(string userid, int sysid, object userState) {
            if ((this.UpdateUserStateBySysIDOperationCompleted == null)) {
                this.UpdateUserStateBySysIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateUserStateBySysIDOperationCompleted);
            }
            this.InvokeAsync("UpdateUserStateBySysID", new object[] {
                        userid,
                        sysid}, this.UpdateUserStateBySysIDOperationCompleted, userState);
        }
        
        private void OnUpdateUserStateBySysIDOperationCompleted(object arg) {
            if ((this.UpdateUserStateBySysIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateUserStateBySysIDCompleted(this, new UpdateUserStateBySysIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("OBSoapHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.openbook.com.cn/GetGroupListByDeptID", RequestNamespace="http://www.openbook.com.cn/", ResponseNamespace="http://www.openbook.com.cn/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetGroupListByDeptID(int did) {
            object[] results = this.Invoke("GetGroupListByDeptID", new object[] {
                        did});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetGroupListByDeptIDAsync(int did) {
            this.GetGroupListByDeptIDAsync(did, null);
        }
        
        /// <remarks/>
        public void GetGroupListByDeptIDAsync(int did, object userState) {
            if ((this.GetGroupListByDeptIDOperationCompleted == null)) {
                this.GetGroupListByDeptIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetGroupListByDeptIDOperationCompleted);
            }
            this.InvokeAsync("GetGroupListByDeptID", new object[] {
                        did}, this.GetGroupListByDeptIDOperationCompleted, userState);
        }
        
        private void OnGetGroupListByDeptIDOperationCompleted(object arg) {
            if ((this.GetGroupListByDeptIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetGroupListByDeptIDCompleted(this, new GetGroupListByDeptIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openbook.com.cn/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.openbook.com.cn/", IsNullable=false)]
    public partial class OBSoapHeader : System.Web.Services.Protocols.SoapHeader {
        
        private string nameField;
        
        private string passField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Pass {
            get {
                return this.passField;
            }
            set {
                this.passField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void GetSerialNoCompletedEventHandler(object sender, GetSerialNoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSerialNoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSerialNoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void TryLoginCompletedEventHandler(object sender, TryLoginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TryLoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TryLoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string userid {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void ChangePwdCompletedEventHandler(object sender, ChangePwdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ChangePwdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ChangePwdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void GetAllEmpInfoForPageForOBFACECompletedEventHandler(object sender, GetAllEmpInfoForPageForOBFACECompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllEmpInfoForPageForOBFACECompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllEmpInfoForPageForOBFACECompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public int Records {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void GetAllDeptInfoCompletedEventHandler(object sender, GetAllDeptInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllDeptInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllDeptInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void GetEmpDetailedInfoByUserIDCompletedEventHandler(object sender, GetEmpDetailedInfoByUserIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetEmpDetailedInfoByUserIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetEmpDetailedInfoByUserIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void GetUserInfoByDeptIDCompletedEventHandler(object sender, GetUserInfoByDeptIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUserInfoByDeptIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUserInfoByDeptIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void GetEmpInfoForPageByParentIDCompletedEventHandler(object sender, GetEmpInfoForPageByParentIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetEmpInfoForPageByParentIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetEmpInfoForPageByParentIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public int Records {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void GetAllEmpInfoCompletedEventHandler(object sender, GetAllEmpInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllEmpInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllEmpInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void GetAllUserBySysIDCompletedEventHandler(object sender, GetAllUserBySysIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllUserBySysIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllUserBySysIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void UpdateUserStateBySysIDCompletedEventHandler(object sender, UpdateUserStateBySysIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateUserStateBySysIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateUserStateBySysIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void GetGroupListByDeptIDCompletedEventHandler(object sender, GetGroupListByDeptIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetGroupListByDeptIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetGroupListByDeptIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591